Wrap doc update function with try-catch
yorkie-team/yorkie-codepair pull request #117
Opened 2021-06-07 15:58 UTC by ppeeou

#### What this PR does / why we need it?

Wrap yorkie doc update function with try-catch
 
why?

When using  `deleteByID` `getElementByID`, an error occurs if the node has been deleted by GC.

#### Any background context you want to provide?

#### What are the relevant tickets?

Fixes #77 

### Checklist
- [x] Added relevant tests or not required
- [ ] Didn't break anything

2021-06-09 16:42 UTC, hackerwins requested changes
Thanks for the work.
I am concerned that the scope of `tryIt` is too broad to ignore other errors. And I think it's better to wrap only those methods where we want to intentionally ignore errors.

2021-06-12 07:20 UTC, hackerwins commented
@ppeeou 
Please re-sign me when the correction is complete.

2021-06-12 12:11 UTC, ppeeou commented on .eslintrc.json
> +    "consistent-return": 0
The reason for adding it is as follows.

We're already getting help from typescript, so I think the above configuration is superfluous.🤔

### no-useless-return

![image](https://user-images.githubusercontent.com/10924072/121775300-b7efba00-cbc1-11eb-9c88-0d750433f9a5.png)

If the return statement is deleted, the following error occurs
![image](https://user-images.githubusercontent.com/10924072/121775354-0b620800-cbc2-11eb-89d4-bc0778d018a0.png)


### consistent-return
![image](https://user-images.githubusercontent.com/10924072/121775282-a9a19e00-cbc1-11eb-8637-8c2f32724ee3.png)

2021-06-12 14:03 UTC, hackerwins requested changes
Thank you for the detailed description. Based on your explanation, I've confirmed that when I am modifying the code like below it doesn't cause any problems even if I don't remove the rule.

2021-06-12 14:03 UTC, hackerwins commented on src/components/Editor/DrawingBoard/Canvas/Worker/Worker.ts
> +    }
```suggestion
    try {
      return root.shapes.deleteByID(createID);
    } catch {
      return undefined;
    }
```

2021-06-12 14:03 UTC, hackerwins commented on src/components/Editor/DrawingBoard/Canvas/Worker/Worker.ts
> +    }
```suggestion
    try {
      return root.shapes.getElementByID(createID);
    } catch {
      return undefined;
    }
```

2021-06-12 14:03 UTC, hackerwins commented on .eslintrc.json
> +    "consistent-return": 0
```suggestion
    "import/prefer-default-export": 0
```

2021-06-13 14:48 UTC, ppeeou commented
> Thank you for the detailed description. Based on your explanation, I've confirmed that when I am modifying the code like below it doesn't cause any problems even if I don't remove the rules.

@hackerwins  Thank you for your comments!
In javascript, if the return value does not exist from a function call, it returns `undefined`. Since typescript is inferring this part, I don't think we need to explicitly use 'undefined', so I added the above condition..!

2021-06-13 17:39 UTC, hackerwins requested changes
@ppeeou 

I think the rules we are trying to eliminate here are meaningful and help reduce mistakes. Wouldn't it be better to remove these rules because we don't want to express `return undefined`?

2021-06-13 17:39 UTC, hackerwins commented on src/components/Editor/DrawingBoard/Canvas/Worker/Worker.ts
> +    }
Even though `root.shapes.deleteByID` returns the deleted element, is there any reason why this method didn't return that element?

2021-06-14 15:31 UTC, ppeeou commented
> Even though root.shapes.deleteByID returns the deleted element, is there any reason why this method didn't return that element?

There was no place to use the return value but It would be better to return it as you said :) I fixed it

2021-06-14 17:17 UTC, hackerwins commented
@ppeeou I'm still hesitating whether removing the lint rules would be a good thing for us. 
Can you help me to make more sense?

2021-06-15 17:12 UTC, ppeeou commented
> @ppeeou I'm still hesitating whether removing the lint rules would be a good thing for us.
> Can you help me to make more sense?

I think typescript is inferring the function return value (if undefined ) / (if there is a value). So I tried to remove the explicit use of undefined.

but If someone on the team wants to code more strictly and explicitly,
I'll process it without removing the lint.


method 1,2 don't have to delete the current lint rule
if use it like 3, need to remove the lint rule... my personal preference to use it like 3

### 1 
```js
deleteByID(root: Root, createID: TimeTicket): Shape | undefined {
  let shape;
  try {
    shape = root.shapes.deleteByID(createID);
    return shape;
  } catch {
    return shape;
  }
}
```

### 2
 ```js
deleteByID(root: Root, createID: TimeTicket): Shape | undefined {
    try {
      return root.shapes.deleteByID(createID);
    } catch {
      return undefined;
    }
  }
```

### 3
```js
deleteByID(root: Root, createID: TimeTicket): Shape | undefined { 
  try {
    return root.shapes.deleteByID(createID);
  } catch {
    return;
  }
}
```

2021-06-16 09:27 UTC, hackerwins commented
@ppeeou I think it's better to be more strict with the help of tools(I like the 2nd one).
What are the opinions of @mojosoeun , @dc7303 ?

2021-06-17 13:27 UTC, dc7303 commented
@ppeeou @hackerwins  I agree with both of you and I think it's a reasonable idea. You've asked me for opinions, so I'll share my thoughts.

I personally think disabling lint rules should be avoided. And I think so in this case.

Returning a value from a function means using the returned value in the next logic. To be exaggerated, `return undefined;` is to specify the value to be used in the upper call stack for this function, and `return;` can be seen as the meaning of break. 

Maybe trivial, but sometimes I like code written strictly like this. Because I think it can reduce even the smallest mistakes.

2021-06-17 14:21 UTC, ppeeou commented
@hackerwins @dc7303 Thanks for your comments,👍 I also agree that it should be written strictly.
I'm going to proceed in the direction of not removing lint!

2021-06-17 14:21 UTC, ppeeou commented
@hackerwins @dc7303 Thanks for your comments,👍 I also agree that it should be written strictly.
I'm going to proceed in the direction of not removing lint!

2021-06-17 23:39 UTC, hackerwins approved these changes
LGTM 👍

2021-06-17 23:40 UTC, merged